# Generated by Django 3.2 on 2021-04-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('contry', models.CharField(max_length=255)),
                ('phone_01', models.CharField(max_length=255)),
                ('phone_02', models.CharField(max_length=255)),
                ('email_01', models.CharField(max_length=255)),
                ('email_02', models.CharField(max_length=255)),
            ],
        ),
    ]
