# Generated by Django 3.2 on 2021-04-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intro',
            name='link',
            field=models.CharField(max_length=255),
        ),
    ]
