# Generated by Django 3.2 on 2021-04-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_feature_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='position',
            field=models.CharField(default='left', max_length=15),
            preserve_default=False,
        ),
    ]
