# Generated by Django 3.2 on 2021-04-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_skills_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numbers',
            name='number',
            field=models.IntegerField(),
        ),
    ]
