# Generated by Django 3.2 on 2021-04-26 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_about_the_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='progressbar_color',
            field=models.CharField(default='info', max_length=255),
            preserve_default=False,
        ),
    ]
