# Generated by Django 3.2 on 2021-04-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_skills_progressbar_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=255, null=True)),
                ('contry', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number_01', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number_02', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='social_link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('social_name', models.CharField(max_length=255)),
                ('logo', models.CharField(default='facebook', max_length=255)),
            ],
        ),
    ]
