# Generated by Django 3.2 on 2021-04-28 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_contactinfo_social_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(default='email@email.com', max_length=254),
            preserve_default=False,
        ),
    ]
