# Generated by Django 3.2 on 2021-04-28 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_contactinfo_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='about_the_company',
            new_name='AboutTheCompany',
        ),
    ]
