# Generated by Django 3.2 on 2021-04-29 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_rename_about_the_company_aboutthecompany'),
    ]

    operations = [
        migrations.CreateModel(
            name='Privacy_policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Terms_of_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
            ],
        ),
    ]
