# Generated by Django 3.2 on 2021-04-27 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_category_portfolio_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio_item',
            name='title',
            field=models.CharField(default='safasfsaf', max_length=255),
            preserve_default=False,
        ),
    ]
